CREATE DATABASE IF NOT EXISTS BD_APLICATIVO_MUSICA;
USE BD_APLICATIVO_MUSICA;

CREATE TABLE IF NOT EXISTS ARTISTA(
	CPF VARCHAR(14) PRIMARY KEY,
	NOME VARCHAR(255) NOT NULL,
	EMAIL VARCHAR(255) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	FOTOS BLOB,
	DESCRICAO VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS GENERO(
	NOME VARCHAR(255) PRIMARY KEY,
    DESCRICAO VARCHAR(400)
);

CREATE TABLE IF NOT EXISTS ALBUM(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOTOS BLOB,
    NOME VARCHAR(255) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    AVALIACAO VARCHAR(255) NOT NULL,
    FK_CPF_ARTISTA VARCHAR(14) NOT NULL,
    FOREIGN KEY(FK_CPF_ARTISTA) REFERENCES ARTISTA(CPF)
);

CREATE TABLE IF NOT EXISTS FAIXAS(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAPA BLOB,
    DURACAO VARCHAR(15) NOT NULL,
    NOME VARCHAR(100)NOT NULL,
    LETRA VARCHAR(3000) NOT NULL,
    FK_ID_ALBUM INTEGER NOT NULL,
    FK_NOME_GENERO VARCHAR(255) NOT NULL,
    FOREIGN KEY(FK_ID_ALBUM) REFERENCES ALBUM(ID),
    FOREIGN KEY(FK_NOME_GENERO) REFERENCES GENERO(NOME)
);