CREATE DATABASE IF NOT EXISTS BD_BIBLIOTECA;
USE BD_BIBLIOTECA;

CREATE TABLE IF NOT EXISTS AUTOR(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    AVALIACAO VARCHAR(255),
    QTD_LIVROS INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS LEITOR(
	CPF VARCHAR(14) PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS LIVRO_DIGITAL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    CAPA BLOB,
    DATA_PUBLICACAO DATE NOT NULL,
    AVALIACAO VARCHAR(255),
    FK_CPF_AUTOR VARCHAR(14) NOT NULL,
    FOREIGN KEY(FK_CPF_AUTOR) REFERENCES AUTOR(CPF) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS LIVRO_LEITOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_LIVRO_DIGITAL INTEGER,
    FK_CPF_LEITOR VARCHAR(14),
    FOREIGN KEY (FK_ID_LIVRO_DIGITAL) REFERENCES LIVRO_DIGITAL(ID) ON DELETE CASCADE,
    FOREIGN KEY(FK_CPF_LEITOR) REFERENCES LEITOR(CPF) ON DELETE CASCADE
);