CREATE DATABASE IF NOT EXISTS BD_ENQUETES;
USE BD_ENQUETES;

CREATE TABLE IF NOT EXISTS USUARIO(
	USU_CODIGO INTEGER AUTO_INCREMENT,
    USU_DATA_CADASTRO DATE NOT NULL,
    USU_LOGIN VARCHAR(255) NOT NULL UNIQUE,
    USU_AREA_ATUACAO VARCHAR(500),
    USU_PROFISSAO VARCHAR(200),
    USU_AREA_FORMACAO VARCHAR(500),
    USU_DATANASC DATE NOT NULL,
    USU_ESTADO_CIVIL ENUM("SOLTEIRO","CASADO","DIVORCIADO","VIÚVO") NOT NULL,
    USU_ESTADO VARCHAR(2) NOT NULL,
    USU_ESCOLARIDADE ENUM("FUNDAMENTAL", "MÉDIO", "SUPERIOR"),
    USU_EMAIL VARCHAR(255) NOT NULL UNIQUE,
    USU_SENHA VARCHAR(255) NOT NULL,
    USU_NOME VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_CODIGO)

);


CREATE TABLE IF NOT EXISTS ENQUETE(
	ENQ_CODIGO INTEGER AUTO_INCREMENT,
    ENQ_DATA_FINAL DATE,
    ENQ_DATA_INICIAL DATE NOT NULL,
    ENQ_DESCRICAO VARCHAR(255) NOT NULL,
    ENQ_NOME VARCHAR(255) NOT NULL,
    FK_USU_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(ENQ_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE

);

CREATE TABLE IF NOT EXISTS USUARIO_RESPONDE_ENQUETE(
	URE_CODIGO INTEGER AUTO_INCREMENT, 
    URE_DATA DATE NOT NULL,
    FK_USU_CODIGO INTEGER,
    FK_ENQ_CODIGO INTEGER,
    PRIMARY KEY(URE_CODIGO),
    FOREIGN KEY(FK_USU_CODIGO) REFERENCES USUARIO(USU_CODIGO) ON DELETE CASCADE,
	FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE

);


CREATE TABLE IF NOT EXISTS PERGUNTAS(
	PER_CODIGO INTEGER AUTO_INCREMENT,
    PER_DESCRICAO VARCHAR(255) NOT NULL UNIQUE,
    FK_ENQ_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(PER_CODIGO),
    FOREIGN KEY(FK_ENQ_CODIGO) REFERENCES ENQUETE(ENQ_CODIGO) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPOSTAS(
	RES_CODIGO INTEGER AUTO_INCREMENT,
    RES_DESCRICAO VARCHAR(255) NOT NULL UNIQUE, 
    RES_CERTA VARCHAR(1)NOT NULL,
    FK_PER_CODIGO INTEGER NOT NULL,
    PRIMARY KEY(RES_CODIGO),
    FOREIGN KEY(FK_PER_CODIGO) REFERENCES PERGUNTAS(PER_CODIGO) ON DELETE CASCADE
);
SELECT* FROM USUARIO;
INSERT INTO USUARIO( USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, 
USU_SENHA, USU_NOME)
VALUES("2025-09-23", "liviabbispo_23", "Economia", "Auditora Fiscal", "Economia", "2009-02-16","SOLTEIRO", "SP", "SUPERIOR", "liviabbispo@gmail.com",
 "160022009.", "Livia Bussaglia Bispo");
 INSERT INTO USUARIO( USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, 
USU_SENHA, USU_NOME)
VALUES("2025-09-27", "renan_230", "Investimento", "Investidor", " Finanças e Negócios", "2008-02-14","SOLTEIRO", "SP", "SUPERIOR", "renanfonseca@gmail.com",
 "140022008.", "Renan Soares Fonseca");
  INSERT INTO USUARIO( USU_DATA_CADASTRO, USU_LOGIN, USU_AREA_ATUACAO, USU_PROFISSAO, USU_AREA_FORMACAO, USU_DATANASC, USU_ESTADO_CIVIL, USU_ESTADO, USU_ESCOLARIDADE, USU_EMAIL, 
USU_SENHA, USU_NOME)
 VALUES("2025-09-29", "anacarolina_200", "Direito", "Advogada", "Direito", "1980-09-12","CASADO", "SP", "SUPERIOR", "anacbispo@gmail.com",
 "12091980.", "Ana Carolina Bussaglia Bispo");
 
SELECT* FROM ENQUETE;
INSERT INTO ENQUETE( ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES("2025-10-01", "2025-10-02", "Qual o nome do cantor que canta 'Te Vivo'?", "Cantor", 1);
INSERT INTO ENQUETE( ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES("2025-10-01", "2025-10-08", "Qual a cor da grama?", "Cor", 2);
 INSERT INTO ENQUETE( ENQ_DATA_FINAL, ENQ_DATA_INICIAL, ENQ_DESCRICAO, ENQ_NOME, FK_USU_CODIGO)
VALUES("2025-10-01", "2025-10-04", "Qual o país mais populoso do mundo?", "País", 3);
 
 
SELECT* FROM USUARIO_RESPONDE_ENQUETE;
INSERT INTO USUARIO_RESPONDE_ENQUETE( URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES("2025-10-01", 1, 1);
INSERT INTO USUARIO_RESPONDE_ENQUETE( URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES("2025-10-05", 2, 2);
INSERT INTO USUARIO_RESPONDE_ENQUETE( URE_DATA, FK_USU_CODIGO, FK_ENQ_CODIGO)
VALUES("2025-10-03", 3, 3);

SELECT* FROM PERGUNTAS;
INSERT INTO PERGUNTAS( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("Qual cantor canta 'Te Vivo'?", 1);
INSERT INTO PERGUNTAS( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("Qual a cor da grama?", 2);
INSERT INTO PERGUNTAS( PER_DESCRICAO, FK_ENQ_CODIGO)
VALUES("Qual o país mais populoso do mundo?", 3);


SELECT* FROM RESPOSTAS;
INSERT INTO RESPOSTAS( RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("Resposta do cantor", "A", 1);
INSERT INTO RESPOSTAS( RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("Resposta da grama", "B", 2);
INSERT INTO RESPOSTAS( RES_DESCRICAO, RES_CERTA, FK_PER_CODIGO)
VALUES("Resposta do país", "C", 1);

UPDATE RESPOSTAS
SET FK_PER_CODIGO =3
WHERE RES_CODIGO= 4;


UPDATE ENQUETE
SET ENQ_DESCRICAO ="PERGUNTAS SOBRE CANTORES"
WHERE ENQ_CODIGO= 1;

UPDATE ENQUETE
SET ENQ_DESCRICAO ="PERGUNTAS SOBRE CORES"
WHERE ENQ_CODIGO= 2;

UPDATE ENQUETE
SET ENQ_DESCRICAO ="PERGUNTAS SOBRE PAÍSES"
WHERE ENQ_CODIGO= 3;

UPDATE RESPOSTAS
SET RES_DESCRICAO ="Luan Santana"
WHERE RES_CODIGO= 1;

UPDATE RESPOSTAS
SET RES_DESCRICAO="Verde"
WHERE RES_CODIGO= 3;

UPDATE RESPOSTAS
SET RES_DESCRICAO ="India"
WHERE RES_CODIGO= 4;