CREATE DATABASE IF NOT EXISTS BD_GESTAO_MERCADO;
USE BD_GESTAO_MERCADO;

CREATE TABLE IF NOT EXISTS CATEGORIA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR(1000)
);

CREATE TABLE IF NOT EXISTS FORNECEDOR(
	CNPJ VARCHAR(20) PRIMARY KEY,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    AVALIACAO VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    VALOR DOUBLE NOT NULL,
    DESCRICAO VARCHAR(255),
    VALIDADE DATE,
    QTD_ESTOQUE INTEGER NOT NULL,
    FOTOS BLOB,
    FK_ID_CATEGORIA INTEGER NOT NULL,
    FOREIGN KEY(FK_ID_CATEGORIA) REFERENCES CATEGORIA(ID)
);

CREATE TABLE IF NOT EXISTS PRODUTO_FORNECEDOR(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_PRODUTO INTEGER NOT NULL,
    FK_CNPJ_FORNECEDOR VARCHAR(20),
    FOREIGN KEY(FK_ID_PRODUTO) REFERENCES PRODUTO(ID),
    FOREIGN KEY(FK_CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);
