CREATE DATABASE IF NOT EXISTS BD_PROJETOS;
USE BD_PROJETOS;

CREATE TABLE IF NOT EXISTS PROJETO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    ORCAMENTO DOUBLE NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIO(
	CPF VARCHAR(14) PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    FUNCAO VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS TAREFA(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255) NOT NULL,
    FK_ID_PROJETO INTEGER NOT NULL,
    FOREIGN KEY(FK_ID_PROJETO) REFERENCES PROJETO(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS RESPONSAVEL(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ID_TAREFA INTEGER NOT NULL,
    FK_CPF_FUNCIONARIO VARCHAR(14),
    FOREIGN KEY(FK_ID_TAREFA) REFERENCES TAREFA(ID) ON DELETE CASCADE,
    FOREIGN KEY(FK_CPF_FUNCIONARIO) REFERENCES FUNCIONARIO(CPF) ON DELETE CASCADE
    );


):