CREATE DATABASE IF NOT EXISTS BD_RESERVA_PASSAGENS;
USE BD_RESERVA_PASSAGENS;

CREATE TABLE IF NOT EXISTS PASSAGEIROS(
	CPF VARCHAR(14) PRIMARY KEY, 
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS VOO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    MAPA_AVIAO BLOB,
    COMPANHIA VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS ASSENTO(
	ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NUMERO_ASSENTO INTEGER NOT NULL,
    VALOR_ASSENTO DOUBLE NOT NULL,
    FK_CPF_PASSAGEIROS VARCHAR(14) NOT NULL,
    FK_ID_VOO INTEGER NOT NULL,
    FOREIGN KEY (FK_CPF_PASSAGEIROS) REFERENCES PASSAGEIROS(CPF),
    FOREIGN KEY (FK_ID_VOO) REFERENCES VOO(ID)
);
    
    
    
    