USE BD_SUPERMERCADO_FUNCIONARIO_PRODUTO_CONSUMIDOR;

INSERT INTO SUPERMERCADO(SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("12345678000101", "Supermercado Grick", "19999999999","gricktambau@email.com", "Grick Street", "10000","TambaCity", "SP");

iNSERT INTO SUPERMERCADO(SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ('98765432000199', 'A Economia Distribuidora de Alimentos',"19999999998", 'aeconomia@email.com', 'Avenida Central', 250, 'São Paulo', 'SP');

INSERT INTO SUPERMERCADO(SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ('11223344000155', 'Preço Justo Supermercados S.A.', "19988889", 'contato@precojusto.com', 'Rua das Flores', 15, 'Campinas', 'SP');

INSERT INTO SUPERMERCADO(SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ('66778899000100', 'Distribuidora Bom Dia LTDA', "19949383929", 'bomdia@email.com.br', 'Travessa da Saudade', 789, 'Ribeirão Preto', 'SP');

INSERT INTO SUPERMERCADO(SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ('54321098000122', 'Mega Desconto de Alimentos', "1999569999", 'sac@megadesconto.net', 'Estrada Velha', 3000, 'Guarulhos', 'SP');

SELECT *FROM SUPERMERCADO;

INSERT INTO PRODUTO(PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ("242424435", "Arroz 5KG", 5, 500, 26.90, "2025-12-25");

INSERT INTO PRODUTO(PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ('7891234567890', 'Café Extra Forte 500g', 0.5, 1200, 15.50, '2026-06-10');

INSERT INTO PRODUTO(PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ('0011223344556', 'Óleo de Soja 900ml', 0.9, 850, 7.99, '2025-08-01');

iNSERT INTO PRODUTO(PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ('9988776655443', 'Leite Integral UHT 1L', 1.0, 3000, 5.25, '2025-04-20');

INSERT INTO PRODUTO(PRO_CODIGO_BARRAS, PRO_NOME, PRO_PESO, PRO_QUANTIDADE, PRO_PRECO, PRO_DATA_VALIDADE)
VALUES ('1357924680011', 'Macarrão Espaguete 500g', 0.5, 1500, 4.30, '2027-01-15');

SELECT *FROM PRODUTO;

INSERT INTO CONSUMIDOR( CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES("45494721892", "Livia Bispo", "1998736272", "liviabbispo@gmail.com");

INSERT INTO CONSUMIDOR(CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES('12345678901', 'João Silva', '11987654321', 'joao.silva@outlook.com');

INSERT INTO CONSUMIDOR(CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES('98765432109', 'Mariana Costa Santos', '21912345678', 'mariana.cs@email.com');

INSERT INTO CONSUMIDOR(CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES('44455566677', 'Pedro Almeida', '31900001111', 'pedro.a@uol.com.br');

INSERT INTO CONSUMIDOR(CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES('00011122233', 'Sofia Mendes', '81955554444', 'sofia_mendes@corp.com');


SELECT *FROM CONSUMIDOR;

INSERT INTO FUNCIONARIO( FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATdA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES("9875432100", "José Vanderlei", "1985-03-12", "1198709817", "ze_varnderlei@email.com", "carteira_ze_vanderlei.pdf", "1234", "56789", "2020-01-15", "44 horas", "12345678000101");

INSERT INTO FUNCIONARIO(FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATdA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES('11122233344', 'Ana Paula de Souza', '1995-10-20', '11998765432', 'ana.souza@supergrick.com', 'CTPS-11122233344', '0001', '101010', '2022-05-10', '40 horas', '12345678000101');

INSERT INTO FUNCIONARIO(FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATdA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES('55566677788', 'Carlos Eduardo Lima', '1978-01-05', '19912345678', 'carlos.lima@supergrick.com', 'CTPS-55566677788', '4321', '98765', '2019-11-20', '44 horas', '12345678000101');

INSERT INTO FUNCIONARIO(FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATdA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES('99900011122', 'Fernanda Rocha', '2000-07-28', '11955554444', 'fernanda.r@supergrick.com', 'CTPS-99900011122', '0101', '123456', '2023-08-01', '30 horas', '12345678000101');

INSERT INTO FUNCIONARIO(FUN_CPF, FUN_NOME, FUN_DATA_NASCIMENTO, FUN_TELEFONE, FUN_EMAIL, FUN_CARTEIRA_TRABALHO, FUN_BANCO_AGENCIA, FUN_BANCO_CONTA, FUN_DATdA_ADMISSAO, FUN_JORNADA_TRABALHO, FK_SUP_CNPJ)
VALUES('32165498700', 'Gabriel Mendes', '1990-04-01', '11944443333', 'gabriel.m@aeconomia.com', 'CTPS-32165498700', '7777', '112233', '2021-03-05', '40 horas', '98765432000199');


SELECT *FROM FUNCIONARIO;

-- Supermercado Grick (12345678000101) vende Arroz (ID 1)
INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES ('12345678000101', 1);

-- A Economia (98765432000199) vende Café (ID 2)
INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES ('98765432000199', 2);

-- Preço Justo (11223344000155) vende Óleo (ID 3)
INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES ('11223344000155', 3);

-- Distribuidora Bom Dia (66778899000100) vende Leite (ID 4)
INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES ('66778899000100', 4);

-- Supermercado Grick (12345678000101) vende Macarrão (ID 5)
INSERT INTO SUPERMERCADO_PRODUTO (FK_SUP_CNPJ, FK_PRO_ID)
VALUES ('12345678000101', 5);

-- Livia Bispo (45494721892) comprou Arroz (ID 1)
INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES ('45494721892', 1);

-- João Silva (12345678901) comprou Café (ID 2)
INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES ('12345678901', 2);

-- Mariana Costa (98765432109) comprou Óleo (ID 3)
INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES ('98765432109', 3);

-- Pedro Almeida (44455566677) comprou Leite (ID 4)
INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES ('44455566677', 4);

-- Sofia Mendes (00011122233) comprou Macarrão (ID 5)
INSERT INTO PRODUTO_CONSUMIDOR (FK_CON_CPF, FK_PRO_ID)
VALUES ('00011122233', 5);

SELECT * FROM SUPERMERCADO;

/* CONSULTAR O AUMENTO DE R$ 2,00 NO PRECO DOS PRODUTOS COM PREÇO ATUAL >= R$ 5,0 */

SELECT PRO_NOME AS "NOME",
	PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
	PRO_PRECO AS "PREÇO ATUAL",
	TRUNCATE((PRO_PRECO +2),2) AS "PRECO COM AJUSTE DE R$ 2,00"
FROM PRODUTO 
WHERE PRO_PRECO >=5;

/* 
CONSULTAR A REDUÇÃO DE 1,00 NO PREÇO DOS PRODUTOS COM PREÇO ATUAL ABAIXO DE R$5,00
*/

SELECT PRO_NOME AS "NOME",
	PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
    PRO_PRECO AS "PREÇO ATUAL",
    TRUNCATE((PRO_PRECO -1),2) AS "PREÇO COM REDUÇÃO DE R$ DE 1,00"
FROM PRODUTO
WHERE PRO_PRECO <=10;

/*CONSULTAR COMO SERIA APLICAR UM DESCONTO DE 10% EM TODOS OS PRODUTOS*/

SELECT PRO_NOME AS "NOME",
	PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
    PRO_PRECO AS "PREÇO ATUAL",
    (PRO_PRECO -(PRO_PRECO* 0.1)) AS "PREÇO COM DESCONTO DE 10%"
FROM PRODUTO;

/*AJUSTAR O ESTOQUE DO PRIMEIRO PRODUTO DIVIDINDO PELA METADE*/

SELECT PRO_ID,
	PRO_NOME,
    PRO_CODIGO_BARRAS, 
    PRO_QUANTIDADE
FROM PRODUTO;

UPDATE PRODUTO
SET PRO_QUANTIDADE = PRO_QUANTIDADE/2
WHERE PRO_ID= 1;

/* CONSULTAR TODOS OS PRODUTOS QUE TENHAM DATA DE VALIDADE ENTRE SETEMBRO DE 2025 E DEZEMBRO DE 2025*/

SELECT PRO_NOME AS "NOME",
	PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
    PRO_DATA_VALIDADE AS "DATA DE VALIDADE"
FROM PRODUTO
WHERE PRO_DATA_VALIDADE BETWEEN '2025-09-01' AND '2025-12-31';

/* CONSULTAR TODOS OS PRODUTOS QUE TENHAM PREÇO MAIOR QUE R$ 10 OU MENOR QUE R$ 4*/

SELECT PRO_NOME AS 'NOME',
	PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
    PRO_PRECO AS "PREÇO"
FROM PRODUTO
WHERE PRO_PRECO >= 10 OR PRO_PRECO <=4;

/* CONSULTAR OS DDS E TELEFONES DOS CONSUMIDORES SEPARADAMENTE */
SELECT CON_NOME AS "NOME DO CONSUMIDOR",
		CON_CPF AS "CPF DO CONSUMIDOR",
		SUBSTRING(CON_TELEFONE, 1,2) AS "DDD DO TELEFONE",
        SUBSTRING(CON_TELEFONE, 3, 9) AS "NÚMERO DO TELEFONE"
FROM CONSUMIDOR;

/* GERAR UMA FRASE CONCATENANDO: RAZÃO SPCIAL, CNPJ, TELEFONE E EMAIL*/

/*GERAR UMA FRASE CONCATENANDO:
RAZÃO SOCIAL DO SUPERMERCADO, CNPJ, TELEFONE E EMAIL*/
SELECT CONCAT("RAZÃO SOCIAL: ", 
				CONCAT(SUP_RAZAO_SOCIAL, 
						CONCAT(" | CNPJ: ", 
								CONCAT(SUP_CNPJ, 
										CONCAT(" | TELEFONE: ", 
												CONCAT(SUP_TELEFONE, 
														CONCAT(" | EMAIL: ", SUP_EMAIL))))))) AS FRASE
FROM SUPERMERCADO;

/* GERAR UMA CONSULTA QUE VERIFICA O STATUS DO ESTOQUE DOS PRODUTOS
REGRAS:
1) QUANTIDADE <=25: ESTOQUE BAIXO
2) QUANTIDADE > 25 E QUANTIDADE <=100: ESTOQUE MÉDIO
3) QUANTIDADE> 100: ESTOQUE ALTO*/

SELECT PRO_NOME AS "NOME",
		PRO_CODIGO_BARRAS AS "CODIGO DE BARRAS",
        PRO_QUANTIDADE AS "QUANTIDADE",
        CASE
			WHEN PRO_QUANTIDADE <= 25 THEN "ESTOQUE BAIXO"
            WHEN PRO_QUANTIDADE > 25 AND PRO_QUANTIDADE < 100 THEN "ESTOQUE MÉDIO"
            WHEN PRO_QUANTIDADE >= 100 THEN "ESTOQUE ALTO"
		END AS "NÍVEL DE ESTOQUE"
FROM PRODUTO;

/* GERAR UMA CONSULTA QUE VERIFICA O STATUS DO PESO DOS PRODUTOS
REGRAS:
1) PESO <=5: PESO BAIXO
2) PESO > 5 E QUANTIDADE <=100: ESTOQUE MÉDIO
3) PESO >= 50: ESTOQUE ALTO*/

SELECT PRO_NOME AS "NOME DO PRODUTO",
PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
PRO_QUANTIDADE AS "QUANTIDADE", 
PRO_DATA_VALIDADE AS "DATA DE VALIDADE",
PRO_PESO AS "PESO DO PRODUTO",
CASE
	WHEN PRO_PESO<= 5 THEN "PESO BAIXO"
    WHEN PRO_PESO > 5 AND PRO_PESO<= 50 THEN "PESO MÉDIO"
    WHEN PRO_PESO >50 THEN "PESO ALTO"
END AS "CLASSIFICAÇÃO DO PESO"
FROM PRODUTO;

/*CONTAR QUANTOS CONSUMIDORES TEMOS CADASTRADOS*/
SELECT COUNT(*)
FROM CONSUMIDOR;

SELECT COUNT(*)
FROM SUPERMERCADO;

SELECT COUNT(*)
FROM FUNCIONARIO;

SELECT COUNT(*)
FROM PRODUTO;

/* SOMAR O PREÇO TOTAL DE TODOS OS PRODUTOS CADASTRADOS*/

SELECT SUM(PRO_PRECO)
FROM PRODUTO;

SELECT CONCAT("R$ ", TRUNCATE(SUM(PRO_PRECO),2)) AS "SOMA TOTAL"
FROM PRODUTO;

/* CALCULAR  A MÉDIA DE PREÇOS DOS PRODUTOS */

SELECT AVG(PRO_PRECO)
FROM PRODUTO;



SELECT CONCAT("R$", TRUNCATE(AVG(PRO_PRECO),2)) AS "MÉDIA DE PREÇO"
FROM PRODUTO;

/*SELECIONAR O PRODUTO MAIS CARO*/

SELECT MAX(PRO_PRECO)
FROM PRODUTO;

/* SELECIONAR O ESTOQUE COM MAIOR QUANTIDADE*/
SELECT MAX(PRO_QUANTIDADE)
FROM PRODUTO;

/*SELECIONAR O PRODUTO MAIS BARATO*/

SELECT MIN(PRO_PRECO)
FROM PRODUTO;

/* SELECIONAR O ESTOQUE COM MENOR QUANTIDADE*/
SELECT MIN(PRO_QUANTIDADE)
FROM PRODUTO;


/* SELECIONAR A DATA E HORA ATUAL*/
SELECT NOW() FROM DUAL;

SELECT FUN_NOME AS "NOME DO FUNCIONÁRIO",
	DATE_FORMAT(FUN_DATA_NASCIMENTO, " %d/%m/%Y") AS "DATA DE NASCIMENTO",
	TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM FUNCIONARIO;

/*FUNÇÕES MATEMÁTICAS
ABS- VALOR ABSOLUTO DE UM NÚMERO
RPUND - ARREDONDAR
POWER- POTÊNCIA*/

SELECT ABS(-10),
	ROUND(PRO_PRECO) AS "PREÇO ARREDONDADO",
    POWER(PRO_PRECO, 2) AS "PRECO ELEVADOS AO QUADRADO"
FROM PRODUTO;

/*UPPER, LOWER, TRIM*/

SELECT UPPER(FUN_NOME) AS "MAIÚSCULAS",
	   LOWER(FUN_NOME) AS "MINÚSCULAS",
       TRIM("       Livia") AS "TIRANDO ESPAÇOS"
FROM FUNCIONARIO;
/*GROUP BY*/
SELECT PRO_QUANTIDADE,
COUNT(*) AS  "REPETIÇÕES"
FROM PRODUTO
GROUP BY PRO_QUANTIDADE;

/*UNION*/
SELECT FUN_NOME,
FUN_CPF
FROM FUNCIONARIO
UNION
SELECT FUN_NOME,
FUN_CPF
FROM FUNCIONARIO;


/*UNION*/
SELECT PRO_NOME
FROM PRODUTO
UNION ALL
SELECT "Arroz 5KG"
FROM DUAL
UNION ALL
SELECT "IOGURT DO BOB ESPONJA"
FROM DUAL;

/*SELECT COM WHERE*/
SELECT FUN_NOME AS "NOME DO FUNCIONÁRIO",
FUN_CPF AS "CPF DO FUNCIONÁRIO",
FUN_DATA_NASCIMENTO AS "DATA DE NASCIMENTO",
timestampdiff(YEAR, FUN_DATA_NASCIMENTO,NOW()) AS "IDADE"
FROM FUNCIONARIO
WHERE TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO,NOW()) >=25
AND TIMESTAMPDIFF(YEAR, FUN_DATA_NASCIMENTO,NOW()) <=35;


/*RETORNAR OS FUNCIONARIOS, CONSUMIDORES E SUPERMERCADOS COM EMAIL IGUAL A HOTMAIL OU OUTLOOK*/
SELECT* FROM SUPERMERCADO;

SELECT CON_NOME AS "NOME",
CON_CPF AS "CPF/CNPJ",
CON_TELEFONE AS "TELEFONE",
CON_EMAIL AS "EMAIL",
"CONSUMIDOR" AS "TIPO"
FROM CONSUMIDOR 
WHERE UPPER(CON_EMAIL) LIKE "%HOTMAIL%"
OR UPPER(CON_EMAIL) LIKE "%OUTLOOK%"
UNION 

SELECT FUN_NOME AS "NOME",
FUN_CPF AS "CPF/CNPJ",
FUN_TELEFONE AS "TELEFONE",
FUN_EMAIL AS "EMAIL",
"FUNCIONARIO" as "TIPO"
FROM FUNCIONARIO
WHERE UPPER(FUN_EMAIL) LIKE "%HOTMAIL%"
OR UPPER(FUN_EMAIL) LIKE "%OUTLOOK%"
UNION
SELECT SUP_RAZAO_SOCIAL AS "NOME",
SUP_CNPJ AS "CPF/CNPJ",
SUP_TELEFONE AS "TELEFONE",
SUP_EMAIL AS "EMAIL",
"SUPERMERCADO" as "TIPO"
FROM SUPERMERCADO
WHERE UPPER(SUP_EMAIL) LIKE "%HOTMAIL%"
OR UPPER(SUP_EMAIL) LIKE "%OUTLOOK%";


/*CROSS JOIN:
RETORNAR TODOS OS PRODUTOS DE SUPERMERCADOS QUE SÃO VENDIDOS*/

SELECT PRODUTO.PRO_NOME					AS "NOME",
		PRODUTO.PRO_CODIGO_BARRAS 		AS "CÓDIGO DE BARRAS",
        SUPERMERCADO.SUP_RAZAO_SOCIAL 	AS "RAZÃO SOCIAL"
FROM 	SUPERMERCADO_PRODUTO 
CROSS JOIN SUPERMERCADO
CROSS JOIN PRODUTO
WHERE 		PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID
AND SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ;

/*INNER JOIN
RETORNAR APENAS OS PRODUTOS QUE FORAM COMPRADOS POR ALGUM CONSUMIDOR*/

SELECT PRODUTO_CONSUMIDOR.PCO_ID AS "ID DA COMPRA",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO",
        PRODUTO.PRO_CODIGO_BARRAS AS "CÓDIGO DE BARRAS",
        CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
        CONSUMIDOR.CON_CPF AS "CPF DO CONSUMIDOR"
FROM PRODUTO_CONSUMIDOR
INNER JOIN PRODUTO ON(PRODUTO_CONSUMIDOR.FK_PRO_ID= PRODUTO.PRO_ID)
INNER JOIN CONSUMIDOR ON(PRODUTO_CONSUMIDOR.FK_CON_CPF= CONSUMIDOR.CON_CPF);

/*INNER JOIN:
RETORNAR APENAS OS FUNCIONÁRIOS QUE TRABALHAM EM UM SUPERMERCADO
RETORNAR O NOME O FUNCIONÁRIO E O NOME DO SUPERMERCADO QUE ELE TRABALHA*/

SELECT *FROM FUNCIONARIO;

SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		FUNCIONARIO.FUN_NOME AS "NOME DO FUNCIONARIO"
FROM SUPERMERCADO
INNER JOIN FUNCIONARIO ON(SUPERMERCADO.SUP_CNPJ= FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCICIO 2 INNER JOIN:
RETORNAR APENAS O NOME DO PRODUTO QUE EXISTAM EM UM SUPERMERCADO
RETORNAR O NOME DO PRODUTO E O NOME DO SUPERMERCADO QUE ELE ESTÁ DISPONÍVEL*/

SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO"
FROM SUPERMERCADO_PRODUTO
INNER JOIN PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID)
INNER JOIN SUPERMERCADO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*LEFT JOIN*/
INSERT INTO PRODUTO(PRO_CODIGO_BARRAS,
			PRO_NOME,
            PRO_PESO,
            PRO_QUANTIDADE,
            PRO_PRECO,
            PRO_DATA_VALIDADE)
VALUES      ("33333333", 
            "KITKAT", 
            "30",
            "1500", 
            4.50,
            "2026-01-01");
            
            
SELECT PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM PRODUTO
LEFT JOIN SUPERMERCADO_PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID)
LEFT JOIN SUPERMERCADO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

select*from SUPERMERCADO;

/*RIGHT JOIN*/
SELECT PRODUTO.PRO_NOME,
		SUPERMERCADO.SUP_RAZAO_SOCIAL
FROM PRODUTO
RIGHT JOIN SUPERMERCADO_PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID)
RIGHT JOIN SUPERMERCADO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ);

/*SELECT COM LEFT JOIN E RIGHT JOIN*/
SELECT *
FROM (
		SELECT S.SUP_RAZAO_SOCIAL AS RAZAO_SOCIAL,
				F.FUN_NOME AS NOME_FUNCIONARIO,
                P.PRO_NOME AS NOME_PRODUTO,
                C.CON_NOME AS NOME_CONSUMIDOR
		FROM SUPERMERCADO S
        LEFT JOIN FUNCIONARIO F ON (S.SUP_CNPJ= F.FK_SUP_CNPJ)
        LEFT JOIN SUPERMERCADO_PRODUTO SP ON(S.SUP_CNPJ= SP.FK_SUP_CNPJ)
        LEFT JOIN PRODUTO P ON(SP.FK_PRO_ID= P.PRO_ID)
        LEFT JOIN PRODUTO_CONSUMIDOR PC ON( P.PRO_ID=PC.FK_PRO_ID)
        LEFT JOIN CONSUMIDOR C ON(PC.FK_CON_CPF=C.CON_CPF)
        UNION
        SELECT S.SUP_RAZAO_SOCIAL AS RAZAO_SOCIAL,
				F.FUN_NOME AS NOME_FUNCIONARIO,
                P.PRO_NOME AS NOME_PRODUTO,
                C.CON_NOME AS NOME_CONSUMIDOR
		FROM SUPERMERCADO S
        RIGHT JOIN FUNCIONARIO F ON (S.SUP_CNPJ= F.FK_SUP_CNPJ)
        RIGHT  JOIN SUPERMERCADO_PRODUTO SP ON(S.SUP_CNPJ= SP.FK_SUP_CNPJ)
        RIGHT  JOIN PRODUTO P ON(SP.FK_PRO_ID= P.PRO_ID)
        RIGHT  JOIN PRODUTO_CONSUMIDOR PC ON( P.PRO_ID=PC.FK_PRO_ID)
		RIGHT  JOIN CONSUMIDOR C ON(PC.FK_CON_CPF=C.CON_CPF)
)SELECT_EXTERNO
ORDER BY SELECT_EXTERNO.RAZAO_SOCIAL ASC,
		 SELECT_EXTERNO.NOME_FUNCIONARIO DESC,
         SELECT_EXTERNO.NOME_PRODUTO    ASC,
         SELECT_EXTERNO.NOME_CONSUMIDOR DESC;
         
		/*INNER JOIN*/
         
/*exercício 1*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO"
FROM SUPERMERCADO_PRODUTO
INNER JOIN SUPERMERCADO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID);


/*EXERCÍCIO 2*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		FUNCIONARIO.FUN_NOME AS "NOME DO FUNCIONARIO"
FROM SUPERMERCADO
INNER JOIN FUNCIONARIO ON(SUPERMERCADO.SUP_CNPJ= FUNCIONARIO.FK_SUP_CNPJ);

/*EXERCÍCIO 3*/
SELECT CONSUMIDOR.CON_NOME AS "Nome do consumidor",
		PRODUTO.PRO_NOME AS "Nome do produto"
FROM PRODUTO_CONSUMIDOR
INNER JOIN CONSUMIDOR ON (CONSUMIDOR.CON_CPF= PRODUTO_CONSUMIDOR.FK_CON_CPF)
INNER JOIN PRODUTO ON(PRODUTO.PRO_ID= PRODUTO_CONSUMIDOR.FK_PRO_ID);


/*EXERCICIO 4*/
SELECT PRODUTO.PRO_NOME AS "Nome do produto",
		CONSUMIDOR.CON_NOME AS "Nome do consumidor"
FROM PRODUTO_CONSUMIDOR
INNER JOIN CONSUMIDOR ON (CONSUMIDOR.CON_CPF= PRODUTO_CONSUMIDOR.FK_CON_CPF)
INNER JOIN PRODUTO ON(PRODUTO.PRO_ID= PRODUTO_CONSUMIDOR.FK_PRO_ID);

/*EXERCÍCIO 5*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		COUNT(PRODUTO.PRO_ID) AS "QUANTIDADE DO PRODUTO"
FROM SUPERMERCADO_PRODUTO
INNER JOIN SUPERMERCADO ON (SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
INNER JOIN PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID)
GROUP BY SUPERMERCADO.SUP_RAZAO_SOCIAL;


/*LEFT JOIN*/

/*EXECICIO 1*/
SELECT * FROM SUPERMERCADO;

		SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
        PRODUTO.PRO_NOME AS "NOME DO PRODUTO"
FROM SUPERMERCADO
LEFT JOIN SUPERMERCADO_PRODUTO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
LEFT JOIN PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*EXERCICIO 2*/

SELECT FUNCIONARIO.FUN_NOME AS "NOME DO FUNCIONÁRIO",
		SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO"
FROM FUNCIONARIO
LEFT JOIN SUPERMERCADO ON( SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);


	/*EXERCICIO 3*/
INSERT INTO CONSUMIDOR(CON_CPF, CON_NOME, CON_TELEFONE, CON_EMAIL)
VALUES('98765432199', 'Mariah  Santana', '88912345678', 'mariah.s@email.com');
    

SELECT CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
		PRODUTO.PRO_NOME AS "NOME DOS PRODUTOS"
FROM CONSUMIDOR
LEFT JOIN PRODUTO_CONSUMIDOR ON(CONSUMIDOR.CON_CPF= PRODUTO_CONSUMIDOR.FK_CON_CPF)
LEFT JOIN PRODUTO ON(PRODUTO.PRO_ID= PRODUTO_CONSUMIDOR.FK_PRO_ID);


/*EXERCICIO 4 */
SELECT PRODUTO.PRO_NOME AS "NOME DOS PRODUTOS",
		CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR"
FROM PRODUTO
LEFT JOIN PRODUTO_CONSUMIDOR ON(PRODUTO.PRO_ID= PRODUTO_CONSUMIDOR.FK_PRO_ID)
LEFT JOIN CONSUMIDOR ON(CONSUMIDOR.CON_CPF= PRODUTO_CONSUMIDOR.FK_CON_CPF);

/*EXERCICIO 5*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
FUNCIONARIO.FUN_NOME AS "NOME DO FUNCIONÁRIO"
FROM SUPERMERCADO
LEFT JOIN FUNCIONARIO ON( SUPERMERCADO.SUP_CNPJ = FUNCIONARIO.FK_SUP_CNPJ);


/*RIGTH JOIN*/

/*EXERCICIO 1*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		PRODUTO.PRO_NOME AS "NOME DOS PRODUTOS"
FROM SUPERMERCADO
RIGHT JOIN SUPERMERCADO_PRODUTO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
RIGHT JOIN PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID);

/*EXERCICIO 2*/
SELECT CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO"
FROM CONSUMIDOR
RIGHT JOIN PRODUTO_CONSUMIDOR ON(CONSUMIDOR.CON_CPF= PRODUTO_CONSUMIDOR.FK_CON_CPF)
RIGHT JOIN PRODUTO ON (PRODUTO.PRO_ID= PRODUTO_CONSUMIDOR.FK_PRO_ID);

/*EXERCICIO 3*/
SELECT FUNCIONARIO.FUN_NOME AS "NOME FUNCIONARIO",
SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO"
FROM FUNCIONARIO
RIGHT JOIN SUPERMERCADO ON( FUNCIONARIO.FK_SUP_CNPJ=SUPERMERCADO.SUP_CNPJ);

/*EXERCICIO 4*/
SELECT SUPERMERCADO.SUP_RAZAO_SOCIAL AS "NOME DO SUPERMERCADO",
		PRODUTO.PRO_NOME AS "NOME DOS PRODUTOS"
FROM SUPERMERCADO
RIGHT JOIN SUPERMERCADO_PRODUTO ON(SUPERMERCADO.SUP_CNPJ= SUPERMERCADO_PRODUTO.FK_SUP_CNPJ)
RIGHT JOIN PRODUTO ON(PRODUTO.PRO_ID= SUPERMERCADO_PRODUTO.FK_PRO_ID);


/*EXERCICIO 5*/
SELECT CONSUMIDOR.CON_NOME AS "NOME DO CONSUMIDOR",
		PRODUTO.PRO_NOME AS "NOME DO PRODUTO"
FROM CONSUMIDOR
RIGHT JOIN PRODUTO_CONSUMIDOR ON(CONSUMIDOR.CON_CPF= PRODUTO_CONSUMIDOR.FK_CON_CPF)
RIGHT JOIN PRODUTO ON (PRODUTO.PRO_ID= PRODUTO_CONSUMIDOR.FK_PRO_ID);


/*SELECIONAR APENAS OS PRODUTOS QUE POSSUAM REGISTRO EM UM SUPERMERCADO E QUE FORAM COMPRADOS POR UM CONSUMIDOR*/
SELECT P.PRO_NOME 			AS "NOME DO PRODUTO",
	   P.PRO_CODIGO_BARRAS 	AS "CÓDIGO DE BARRAS",
	   P.PRO_PRECO 			AS "PREÇO DO PRODUTO"
FROM PRODUTO P
WHERE P.PRO_ID IN (SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND P.PRO_ID IN (SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);

/*SELECIONAR APENAS OS PRODUTOS QUE NÃO POSSUEM REGISTRO EM UM SUPERMERCADO E QUE NÃO FORAM COMPRADOS POR UM CONSUMIDOR*/

SELECT P.PRO_NOME 			AS "NOME DO PRODUTO",
	   P.PRO_CODIGO_BARRAS 	AS "CÓDIGO DE BARRAS",
	   P.PRO_PRECO 			AS "PREÇO DO PRODUTO"
FROM PRODUTO P
WHERE P.PRO_ID NOT IN  (SELECT SP.FK_PRO_ID FROM SUPERMERCADO_PRODUTO SP)
AND P.PRO_ID NOT IN (SELECT PC.FK_PRO_ID FROM PRODUTO_CONSUMIDOR PC);


/*SELECIONAR OS SUPERMERCADOS QUE TEM O PREÇO DE TODOS OS PRODUTOS MENOR QUE 10*/

SELECT S.SUP_RAZAO_SOCIAL
FROM SUPERMERCADO S
WHERE 10>ALL(
SELECT P.PRO_PRECO
FROM PRODUTO P 
);
SELECT * FROM PRODUTO;

/*LISTAR TODOS OS PRODUTOS CUJO PREÇO SEJA MAIOR QUE O PREÇO DE QUALQUER PRODUTO VENDIDO NO SUPERMERCADO com cnpj 12345678000101*/

SELECT PRO_NOME,
		PRO_PRECO
FROM PRODUTO
WHERE PRO_PRECO> ANY(
SELECT P.PRO_PRECO
FROM PRODUTO P
INNER JOIN SUPERMERCADO_PRODUTO SP
ON (P.PRO_ID = SP.FK_PRO_ID)
WHERE SP.FK_SUP_CNPJ= "12345678000101"
);

/*LISTAR TODOS OS CONSUMIDORES QUE COMPRARAM PELO MENOS UM PRODUTO*/
SELECT C.CON_NOME,
C.CON_CPF
FROM CONSUMIDOR C
WHERE EXISTS (
SELECT 1
FROM PRODUTO_CONSUMIDOR PC
WHERE PC.FK_CON_CPF = C.CON_CPF
);

SELECT C.CON_NOME,
C.CON_CPF
FROM CONSUMIDOR C
WHERE NOT EXISTS (
SELECT 1
FROM PRODUTO_CONSUMIDOR PC
WHERE PC.FK_CON_CPF = C.CON_CPF
);


/*TCL
LINGUAGEM DE CONTROLE DE TRANSAÇÕES:
COMMIT
*/
-- PASSO 1: INICIAR A TRANSAÇÃO

START TRANSACTION;


-- PASSO 2: ESCREVER O COMANDO DML

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("11111111000111", "Supermercado Pontes", "11987654321", "pontes@pontes.com", "Rua do Pontes", "100", "Tambáu", "SP");

-- PASSO 3: SE TUDO DEU CERTO, ENVIA PRO BANCO
COMMIT;



/*TCL
LINGUAGEM DE CONTROLE DE TRANSAÇÕES:
ROLLBACK
*/
-- PASSO 1: INICIAR A TRANSAÇÃO

START TRANSACTION;


-- PASSO 2: ESCREVER O COMANDO DML

INSERT INTO SUPERMERCADO (SUP_CNPJ, SUP_RAZAO_SOCIAL, SUP_TELEFONE, SUP_EMAIL, SUP_ENDERECO_LOGRADOURO, SUP_ENDERECO_NUMERO, SUP_ENDERECO_CIDADE, SUP_ENDERECO_ESTADO)
VALUES ("11111111000111", "Supermercado Pontes", "11987654321", "pontes@pontes.com", "Rua do Pontes", "100", "Tambáu", "SP");

-- PASSO 3: SE DEU ERRO, NÃO ENVIA PRO BANCO
ROLLBACK;