CREATE DATABASE IF NOT EXISTS BD_ALUGUEL_PRODUTOS;
USE BD_ALUGUEL_PRODUTOS;

CREATE TABLE IF NOT EXISTS CLIENTE(
	CLIENTE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL,
    CPF VARCHAR(14) NOT NULL,
    NOME VARCHAR(255) NOT NULL,
    TELEFONE VARCHAR(15) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTO(
	PRODUTO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    DESCRICAO VARCHAR (500) NOT NULL,
    PRECO DECIMAL NOT NULL,
    QTD_DISPONIVEL INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS ALUGUEL(
	ALUGUEL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DATA_ALUGUEL DATE NOT NULL, 
    DATA_DEVOLUCAO DATE NOT NULL,
    VALOR_TOTAL DECIMAL NOT NULL,
    FK_CLIENTE_ID INTEGER NOT NULL,
    FK_PRODUTO_ID INTEGER NOT NULL,
    FOREIGN KEY(FK_CLIENTE_ID) REFERENCES CLIENTE(CLIENTE_ID) ON DELETE CASCADE,
    FOREIGN KEY(FK_PRODUTO_ID) REFERENCES PRODUTO(PRODUTO_ID) ON DELETE CASCADE
    );
    
    -- DML - LINGUAGEM DE MANIPULAÇÃO
    -- INSERT- INSERIR
    
INSERT  INTO CLIENTE (EMAIL, TELEFONE, CPF, NOME)
VALUES ("Email@email.com", "1999999999999", "12345678", "Leo");

INSERT INTO CLIENTE (EMAIL, TELEFONE, CPF, NOME)
VALUES ("liviabbispo@gmail.com", "19 99136-2035", "454.947.218-92", "Livia Bispo");
    
INSERT INTO CLIENTE(NOME, EMAIL, TELEFONE, CPF)
VALUES("Gabriel", "gabriel@gmail.com", "1999415099", "22222222222");

-- Select -Selecionar 

SELECT * FROM CLIENTE;

-- INSERIR PRODUTOS

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("MacBook M4", "Notebook Apple", 4789.90, 5);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES ("Samsung Galaxy A55", "Celular Smartphone Samsung", 3000, 100);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("iPhone 15", "Smartphone Apple", 10000, 50);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Sony PlayStation 5", "Video Game Sony", 4500, 100);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Microsoft Xbox Series X", "Video Game Microsoft", 4800, 200);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Sony WH-1000XM5", "Fone de Ouvido Noise Cancelling", 1800, 100);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Apple AirPods Pro (2ª Geração)", "Fones de Ouvido Sem Fio (TWS) Apple", 2300, 50);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Apple Watch Series 9 (GPS + Celular)", "Smartwatch Apple ", 6000, 10);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Samsung Galaxy Watch 6 Classic (47mm)", "Smartwatch Samsung ", 3000, 20);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("Dell XPS 13 (i7/16GB RAM/512GB SSD))", "Notebook Ultra Portátil Dell ", 9500, 200);

INSERT INTO PRODUTO(NOME, DESCRICAO, PRECO, QTD_DISPONIVEL)
VALUES("MacBook Pro 14 (Chip M3 Pro/18GB RAM)", "Notebook Premium Apple ", 14000, 50);



SELECT * FROM PRODUTO;

-- INSERIR ALUGUEIS 
SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (DATA_ALUGUEL,
					 DATA_DEVOLUCAO,
                     VALOR_TOTAL, 
                     FK_CLIENTE_ID,
                     FK_PRODUTO_ID)
VALUES 				( "2025-09-24",
					  "2025-10-01",
                      7890,
                      3,
                      2);
                      
INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-09-19", "2025-09-29", 4500,3,4);

SELECT * FROM CLIENTE;
SELECT * FROM PRODUTO;

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-09-15", "2025-10-02", 14000, 1, 11);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-03-10", "2025-03-20", 4790, 3,1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-05-30", "2025-06-09", 10000, 3,3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-01-05", "2025-01-20", 4500, 3,4);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-02-25", "2025-03-05", 4800, 3,5);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-03-24", "2025-04-01", 1800, 1,6);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-04-05", "2025-04-25", 2300, 2,7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-05-15", "2025-05-30", 6000, 4,8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-06-08", "2025-16-18", 3000, 1,9);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-09-21", "2025-10-02", 9500, 3,10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-07-01", "2025-07-10", 14000, 1,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-02-11", "2025-02-21", 4790, 2,1);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-01-21", "2025-01-30", 3000, 3,2);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-04-10", "2025-04-2025", 10000, 4,3);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-03-21", "2025-03-30", 9500, 3,10);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-08-24", "2025-09-24", 14000, 1,11);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-05-28", "2025-06-10", 9500, 2,7);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-09-21", "2025-10-02", 6000, 3,8);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-03-25", "2025-03-30", 3000, 4,9);

INSERT INTO ALUGUEL (DATA_ALUGUEL, DATA_DEVOLUCAO, VALOR_TOTAL, FK_CLIENTE_ID, FK_PRODUTO_ID)
VALUES ( "2025-09-02","2025-09-20", 4500, 2,4);
                      
SELECT * FROM ALUGUEL;
SELECT *FROM PRODUTO;

-- ATUALIZAR UM REGISTRO (UPDATE)

UPDATE PRODUTO
SET PRECO =3500
WHERE PRODUTO_ID= 1;


UPDATE PRODUTO
SET PRECO =10000
WHERE PRODUTO_ID= 2;

UPDATE PRODUTO
SET PRECO =6000
WHERE PRODUTO_ID= 4;

UPDATE PRODUTO
SET PRECO =15000
WHERE PRODUTO_ID= 11;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 45
WHERE PRODUTO_ID= 11;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 200
WHERE PRODUTO_ID= 1;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 90
WHERE PRODUTO_ID= 11;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 100
WHERE PRODUTO_ID= 3;

UPDATE PRODUTO
SET QTD_DISPONIVEL = 30
WHERE PRODUTO_ID= 8;


UPDATE CLIENTE
SET EMAIL = "leo@gmail.com"
WHERE CLIENTE_ID= 1;

UPDATE CLIENTE
SET EMAIL = "livinha@gmail.com"
WHERE CLIENTE_ID= 3;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-10-09"
WHERE ALUGUEL_ID= 3;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-10-07"
WHERE ALUGUEL_ID= 2;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-09-09"
WHERE ALUGUEL_ID= 4;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-11-09"
WHERE ALUGUEL_ID= 5;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-12-12"
WHERE ALUGUEL_ID= 18;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-10-20"
WHERE ALUGUEL_ID= 8;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-11-29"
WHERE ALUGUEL_ID= 6;

UPDATE ALUGUEL
SET DATA_DEVOLUCAO= "2025-10-31"
WHERE ALUGUEL_ID= 11;

-- APAGAR UM REGISTRO(DELETE)

DELETE FROM CLIENTE
WHERE CLIENTE_ID = 1;

DELETE FROM PRODUTO
WHERE PRODUTO_ID = 4;

DELETE FROM ALUGUEL
WHERE ALUGUEL_ID= 3;

SELECT *FROM CLIENTE;

SELECT*FROM CLIENTE
WHERE CLIENTE_ID= 2;


SELECT NOME, PRECO
FROM PRODUTO
WHERE PRODUTO_ID = 3;